version: "3.4"
services:
  personal.libraryapi:
    hostname: Personal
    container_name: Personal
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000"
      - "5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  personal.database:
    image: mongo:latest
    container_name: MongoPersonalDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=CbvrfFhntvrf65
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'
    volumes:
      - "c:\\DB_Data\\Personal\\:/data/db"

  personal.cache:
    image: redis:latest
    container_name: RedisCache
    restart: always
    ports:
      - '6379:6379' 

 
